# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH
# nr-vault Site Set Configuration
# TYPO3 v13+ Site Sets
name: nr-vault
label: 'Vault - Secure Secrets Management'
dependencies: []
